apiVersion: v1
kind: Service
metadata:
  name: camera-collector-webapp
spec:
  selector:
    app: camera-collector-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
